version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/upfilly-api
    overwrite: true
file_exists_behaviour: OVERWRITE
hooks:
  BeforeInstall:

  AfterInstall:
  ApplicationStart:
    - location: start_server.sh
      timeout: 300
      runas: ubuntu
  ApplicationStop:
