module.exports = {
    SubscriptionPlansValidations: require('../Validations/SubscriptionPlansValidations'),
    CardsValidations: require('./CardsValidations'),
    NotificationsValidate: require("./NotificationsValidations"),
    CommonCategoryValidations: require('./CommonCategoryValidations'),
    UserValidations: require('./UsersValidations'),
    ContractValidations: require('./ContractValidations'),
    HiringValidations: require('./HiringValidations'),
    FavouritesValidations: require('./FavouritesValidations'),
    FaqValidations: require("../Validations/FaqValidation"),
    AssignedContractValidations: require('./AssignedContractValidations'),
    ProfileClaimValidations: require('./ProfileClaimValidations'),
    ProfileViewValidations: require('./ProfileViewsValidations'),
    PermissionValidations: require('./PermissionValidations'),
    FreeTrialRequestValidations: require('./FreeTrialRequestValidations'),
    LanguageValidations: require('./LanguagesValidations'),
    CommonDeleteValidations: require('./CommonDeleteValidations'),
    CampaignValidations: require('./CampaignValidations'),
    Points: require('./PointsValidations'),
    Influencer: require('./InfluencerValidations'),
    ReviewsValidations: require("./ReviewsValidations"),
    Referral: require('./ReferralValidations'),
    Settings: require('./SettingsValidations'),
    CampaignResult: require('./CampaignResultValidations'),
    FeaturesValidation: require('./FeaturesValidateions'),
    Permission: require('./PermissionValidations'),
    DiscountValidation: require('./DiscountValidations'),
    ContentManagementValidations: require("./ContentManagementValidations"),
    Smtp: require('./SmtpValidations'),
    ScriptValidations: require('./ScriptValidations'),
    BlogValidations: require("./BlogValidations"),
    ProposalValidations: require("./ProposalValidations"),
    AffiliateManagement: require("./AffiliateManagementValidations"),
    BraintreeValidation: require("./BraintreeValidation"),
    CommissionValidation: require("./CommissionValidation"),
    TrackingValidation: require("./TrackingManagementValidations"),
    StripeValidation: require("./StripeValidation"),
    Product: require("./ProductValidations"),
    MakeOfferValidations: require("./MakeOfferValidations"),
    InviteValidation: require("./InviteValidation"),
    tax:require('./NewTaxVAlidations'),
    AffiliateInviteValidations:require('./AffiliateInviteValidations'),


    // DiscountBraintreeValidation: require("./DiscountBraintreeValidations")
}